services:
  redis:
    image: redis:7.2.4-alpine
    restart: on-failure
    env_file:
      - back-end/.env
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis:/data
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    env_file:
      - back-end/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"

  nats:
    image: nats
    entrypoint: /nats-server
    command: "-js -m 5555"
    ports:
      - "4222:4222"
      - "5555:5555"
    volumes:
      - "js:/tmp/nats/jetstream"

  mos_prom_api:
    image: mos_prom_api:latest
    env_file:
      - back-end/.env
    restart: always
    command: 'uv run uvicorn src.main:app --host 0.0.0.0 --port 8000'
    ports:
      - "8000:8000"
    depends_on:
      nats:
        condition: service_started
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully

    logging:
      driver: "json-file"
      options:
        max-size: "10GB"
        max-file: "3"

  migrations:
    image: mos_prom_api:latest
    env_file:
      - back-end/.env
    restart: no
    command: 'uv run alembic upgrade head'
    depends_on:
      - db

volumes:
  pgdata:
  js:
  redis: